### ISSUE TITLE
Ethernet Container Yang not compiling

### ISSUE THREAD

**Issue by sbarguil** [openBackhaul/ethernetContainer#24] opened 2020-01-15 21:14 UTC
There are errors in Yang File. Not able to compile it using pyang. 

```
pyang -f tree ethernet-container-2-0.yang 
ethernet-container-2-0.yang:1: error: syntax error: illegal keyword: ﻿module ethernet-container-2-0 {
```

**Comment by alexandrustancu** [comment] 2020-01-16 08:16
I believe this is a problem caused by the YANG file being edited under Windows.

You could try the following command first, and then re-run your pyang:

`dos2unix -o ethernet-container-2-0.yang`

It worked for me.

**Comment by Jothi-upashana** [comment] 2020-01-16 14:07
pyang -f tree ethernet-container-2-0.yang 
ethernet-container-2-0.yang:9: error: module "core-model-1-4" not found in search path
module: ethernet-container-2-0

In EthernetContainer_2.0.0-tsp.191123.1240+yang.1, only ethernet-container-2-0.yang found. No core-model.yang found.

**Comment by alexandrustancu** [comment] 2020-01-16 14:19
The core-model-1-4.yang model is under the [core repository](https://github.com/openBackhaul/core/blob/tsp).

**Comment by Jothi-upashana** [comment] 2020-01-16 14:40
Issue resolved. Able to compile YANG using pyang. Thanks.

**Comment by openBackhaul** [comment] 2021-04-08 15:31
YANG has already been corrected.
Existing implementations are basing on the corrected YANG.

Proposal to the 5G-xhaul call on 21st of April:
Just closing the issue

**Closed** 2021-04-21 09:12 UTC
Labels: Proposal_made
